### ISSUE TITLE
Hi David, are you using nvim nightly build for treesitter and lua configs?

### ISSUE THREAD

**Issue by molleweide** [dbalatero/dotfiles-old#6]
Hi David!

Which version of nvim are you using? l am assuming that you are using nightly build or am i wrong?
I read that lua configs and treesitter are under development and only works with nighlty.
I am kind of a newbie with vim and looking at your dotfiles has taught me a lot.
Is the nightly build suppose to be installed by your repo or is it assumed that one does this one ones own?

**Comment by molleweide** [comment]
im looking at this article to see how one can use two nvim versions in parallell.
https://dev.to/creativenull/installing-neovim-nightly-alongside-stable-10d0

Also, a bit off topic:
May I ask you also which iterm color theme you are using?
And is Logic Pro your main daw? I am using a vim-inspired framework called reaper-keys for the Cockos Reaper daw that gives you fully sequential and modal keybindings for the daw. I am trying to help out with the development of the project. With reaper you can do everything in the daw with Lua scripts.

**Comment by molleweide** [comment]
I am going to setup my reaper development workflow w tmuxinator and create a reaper installer script. i'll submit it later when i've got it working.

**Comment by molleweide** [comment]
i just teste my reaper vim together w vim spoon and it works. this pretty much makes the whole daw act Iike vim. 
This is pretty damn cool. I am also using a  desktop app called vimac which gives you vim-easymotion like nav in macos. 

I am also using a  layout on my qmk keyboard where i have all modifier keys put on homerow. i will try to add my karabiner configs. this makes nav in reaper vim nice. i am thinking about building my own dactyl. did you build yours?

**Comment by dbalatero** [comment]
Just install nightly

```
brew uninstall luajit
brew uninstall neovim
brew install luajit --HEAD
brew install neovim --HEAD
```

I did not build my Dactyl, contracted it. Please feel free to use anything from this repo, but I'm not really interested in contributions back. I'd recommend copying bits you like by hand, don't clone these dotfiles and run them against your computer. They do too much to just blindly setup on your machine and I will not support them as out-of-the-box style software like oh-my-zsh, just as fair warning. Glad you're enjoying vim!

**Comment by molleweide** [comment]
Thanks for replying! 
I installed the dotfiles on my second laptop.
I totally understand about controbutions. Thanks for making your dotfiles public. This is awesome!!

**Comment by molleweide** [comment]
Yo David,

Can I ask you if you have a special trick for copying lines from terminal without using your mouse?
Also, I am trying to install kmonad keymapper on osx. It should be able to handle qmk like layers which karabiner does not. Have you tried it?

**Comment by dbalatero** [comment]
I have not tried kmonad - I have a QMK board, but I used Karabiner before that.

I use tmux and tmux has a copy mode, so that's what I do.

**Comment by molleweide** [comment]
Tmux copy!! Thx

**Comment by molleweide** [comment]
Yeah my use case is to mirror my ergodox layers on mac in case i don’t have it with me

**Comment by molleweide** [comment]
LOL tmux vi copy is AMAZING!!

**Comment by molleweide** [comment]
hey I have been using kmonad now for a couple of days now and it is really good. the layers work really well. i have been able to identically mirror my qmk layout on the laptop.
